### ISSUE TITLE
Usage Examples Fails Silently

### ISSUE THREAD

**Issue by dhollenbeck** [rse/node-prince#23] opened 2018-05-29 14:02 UTC
The example in the readme fails silently because you are missing `var util = require('util');` in the example.

I have sumitted a pull request to fix this: https://github.com/rse/node-prince/pull/22/commits

Thanks for your work on this node module.

**Comment by niksajanjic** [comment] 2018-06-26 14:09
To be honest, I don't have that problem, and he is requiring util module inside his source code which is provided by Node (so maybe it's due to Node version we are using). But even if it works, that part of code is deprecated. The problem is that `utils.isArray` function is deprecated in Node 4 version, so he'll have to update that part of code to use `Array.isArray` and then `util` module will no longer be necessary.

**Comment by rse** [comment] 2018-12-26 01:00
Fixed now.

**Closed by rse** 2018-12-26 01:00 UTC
